#!/usr/bin/env python

from utils import *

def setup():
    if not ROOT_SITES:
        print 'Wrong configuration, did you run make_hosting_conf.py before ?'
        return False
    s = open(PATH_VASSAL_TEMPLATE).read()
    s = s.replace('<%app_dir%>', loc_app_dir('%n'))\
            .replace('<%wsgi_dir%>', loc_wsgi_dir('%n'))\
            .replace('<%plugins_dir%>', os.path.join(ROOT_UWSGI, 'plugins'))
    s = '; This file has been generated by setup.py\n\n' + s
    open(PATH_VASSAL_CONF, 'w').write(s)
    return True


if __name__ == '__main__':
    setup()
