#!/usr/bin/env python

from utils import *

def setup():
    if not ROOT_SITES:
        print 'Wrong configuration, did you run make_hosting_conf.py before ?'
        return False
    s = open(PATH_VASSAL_TEMPLATE).read()
    s = s.replace('<%root_sites%>', ROOT_SITES)
    s = '; This file has been generated by setup.py\n\n' + s
    open(PATH_VASSAL_CONF, 'w').write(s)
    return True


if __name__ == '__main__':
    setup()
